INSERT INTO ENDERECO VALUES
(1, 'Oliveira I', '79091-680', 'Campo Grande', NULL,  'Rua Antônio João Escobar', 255, 'MS');

INSERT INTO ROLE VALUES
  (1, 'USER');

INSERT INTO USUARIO_ROLE VALUES
  ('059.732.891-92', 1);

  INSERT INTO ANUNCIO (ANUNCIO_ID, CONDICAO, DESCRICAO, FINALIDADE, VALOR, USUARIO_CPF, ENDERECO_ID) VALUES
    	(1, '', '', '', 1, '059.732.891-92', 1)

SELECT * FROM ENDERECO;
SELECT * FROM USUARIO;
SELECT * FROM ROLE;
SELECT * FROM USUARIO_ROLE;